export const ADD_BILL = 'accounts/ADD_BILL'
export const UPDATE_BILL = 'accounts/UPDATE_BILL'
export const FETCH_BILLS = 'accounts/FETCH_BILLS'
export const FETCH_BILL = 'accounts/FETCH_BILL'
export const INIT_CATEGORIES = 'accounts/INIT_CATEGORIES'
export const INIT_REGULARITIES = 'account/INIT_REGULARITIES'
